# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbms_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 806)
        MainWindow.setMaximumSize(QtCore.QSize(1123, 806))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/bubble-tea.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(205, 165, 129);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 1071, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.titleLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.titleLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.titleLayout.setContentsMargins(0, 0, 0, 0)
        self.titleLayout.setObjectName("titleLayout")
        self.titleLable = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.titleLable.setStyleSheet("font: 75 16pt \"微軟正黑體\";\n"
                                      "")
        self.titleLable.setTextFormat(QtCore.Qt.AutoText)
        self.titleLable.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.titleLable.setObjectName("titleLable")
        self.titleLayout.addWidget(self.titleLable)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 80, 301, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.controlLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.controlLayout.setContentsMargins(0, 0, 0, 0)
        self.controlLayout.setObjectName("controlLayout")
        self.controlLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.controlLabel.setStyleSheet("font: 12pt \"微軟正黑體\";\n"
                                        "background-color: rgb(154, 104, 82);\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-style: outset;\n"
                                        "border-width: 2px;\n"
                                        "border-color: rgb(111, 86, 75);\n"
                                        "padding: 1px;\n"
                                        "border-top-left-radius: 10px;")
        self.controlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlLabel.setObjectName("controlLabel")
        self.controlLayout.addWidget(self.controlLabel)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(29, 470, 1071, 291))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.resultLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.resultLayout.setContentsMargins(0, 0, 0, 0)
        self.resultLayout.setObjectName("resultLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setStyleSheet("font: 12pt \"微軟正黑體\";\n"
                                       "background-color: rgb(253, 248, 220);\n"
                                       "color: rgb(0, 0, 0);\n"
                                       "border-style: inset;\n"
                                       "border-width: 2px;\n"
                                       "border-color: rgb(218, 190, 167);\n"
                                       "padding: 1px;\n"
                                       "border-bottom-left-radius: 10px;\n"
                                       "border-bottom-right-radius: 10px;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.resultLayout.addWidget(self.tableWidget)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(330, 80, 771, 68))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.barLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.barLayout.setContentsMargins(0, 0, 0, 0)
        self.barLayout.setObjectName("barLayout")
        self.barBox = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.barBox.setStyleSheet("font: 12pt \"微軟正黑體\";\n"
                                  "background-color: rgb(255, 239, 213);\n"
                                  "color: rgb(0, 0, 0);\n"
                                  "border-style: inset;\n"
                                  "border-width: 2px;\n"
                                  "border-color: rgb(218, 190, 167);\n"
                                  "padding: 1px;\n"
                                  "border-top-right-radius: 10px;\n"
                                  "height: 60px;")
        self.barBox.setObjectName("barBox")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barBox.addItem("")
        self.barLayout.addWidget(self.barBox)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 140, 301, 111))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.queryLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.queryLayout.setContentsMargins(0, 0, 0, 0)
        self.queryLayout.setObjectName("queryLayout")
        self.queryLable = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.queryLable.setStyleSheet("font: 12pt \"微軟正黑體\";\n"
                                      "background-color: rgb(154, 104, 82);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "border-style: outset;\n"
                                      "border-width: 2px;\n"
                                      "border-color: rgb(111, 86, 75);\n"
                                      "padding: 1px;\n"
                                      "border-bottom-left-radius: 10px;")
        self.queryLable.setAlignment(QtCore.Qt.AlignCenter)
        self.queryLable.setObjectName("queryLable")
        self.queryLayout.addWidget(self.queryLable)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(440, 350, 241, 51))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.buttonLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.serachButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.serachButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.serachButton.setStyleSheet("font: 75 12pt \"微軟正黑體\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(154, 104, 82);\n"
                                        "border-radius: 10px;\n"
                                        "height: 40px;\n"
                                        "border-style: outset;\n"
                                        "border-width: 2px;\n"
                                        "border-color: rgb(111, 86, 75);\n"
                                        "padding: 1px;")
        self.serachButton.setObjectName("serachButton")
        self.buttonLayout.addWidget(self.serachButton)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(30, 430, 1071, 41))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.showLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.showLayout.setContentsMargins(0, 0, 0, 0)
        self.showLayout.setObjectName("showLayout")
        self.showLabel = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.showLabel.setStyleSheet("font: 14pt \"微軟正黑體\";\n"
                                     "background-color: rgb(154, 104, 82);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "border-style: outset;\n"
                                     "border-width: 2px;\n"
                                     "border-color: rgb(111, 86, 75);\n"
                                     "padding: 1px;\n"
                                     "border-top-left-radius: 10px;\n"
                                     "border-top-right-radius: 10px;")
        self.showLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.showLabel.setObjectName("showLabel")
        self.showLayout.addWidget(self.showLabel)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(329, 139, 771, 111))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.inputLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.inputLayout.setContentsMargins(0, 0, 0, 0)
        self.inputLayout.setObjectName("inputLayout")
        self.inputText = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.inputText.setStyleSheet("font: 12pt \"微軟正黑體\";\n"
                                     "background-color: rgb(253, 248, 220);\n"
                                     "color: rgb(0, 0, 0);\n"
                                     "border-style: inset;\n"
                                     "border-width: 2px;\n"
                                     "border-color: rgb(218, 190, 167);\n"
                                     "padding: 1px;\n"
                                     "border-bottom-right-radius: 10px;")
        self.inputText.setObjectName("inputText")
        self.inputLayout.addWidget(self.inputText)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(30, 260, 1071, 81))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.textLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.textLayout.setContentsMargins(0, 0, 0, 0)
        self.textLayout.setObjectName("textLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_9)
        self.textBrowser.setStyleSheet("font: 12pt \"微軟正黑體\";\n"
                                       "color: rgb(255, 255, 255);\n"
                                       "background-color: rgb(197, 158, 124);\n"
                                       "border-style: inset;\n"
                                       "border-width: 2px;\n"
                                       "border-color: rgb(197, 158, 124);\n"
                                       "padding: 1px;\n"
                                       "border-radius: 10px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bubble Tea DBMS"))
        self.titleLable.setText(_translate("MainWindow", "珍 珠 奶 茶 店 資 料 庫 系 統"))
        self.controlLabel.setText(_translate("MainWindow", "查 詢 工 具"))
        self.barBox.setItemText(0, _translate("MainWindow", "MySQL"))
        self.barBox.setItemText(1, _translate("MainWindow", "SELECT-FROM-WHERE"))
        self.barBox.setItemText(2, _translate("MainWindow", "DELETE"))
        self.barBox.setItemText(3, _translate("MainWindow", "INSERT"))
        self.barBox.setItemText(4, _translate("MainWindow", "UPDATE"))
        self.barBox.setItemText(5, _translate("MainWindow", "IN"))
        self.barBox.setItemText(6, _translate("MainWindow", "NOT IN"))
        self.barBox.setItemText(7, _translate("MainWindow", "EXISTS"))
        self.barBox.setItemText(8, _translate("MainWindow", "NOT EXISTS"))
        self.barBox.setItemText(9, _translate("MainWindow", "COUNT"))
        self.barBox.setItemText(10, _translate("MainWindow", "SUM"))
        self.barBox.setItemText(11, _translate("MainWindow", "MAX"))
        self.barBox.setItemText(12, _translate("MainWindow", "MIN"))
        self.barBox.setItemText(13, _translate("MainWindow", "AVG"))
        self.barBox.setItemText(14, _translate("MainWindow", "HAVING"))
        self.queryLable.setText(_translate("MainWindow", "查 詢 關 鍵 字"))
        self.serachButton.setText(_translate("MainWindow", "查 詢"))
        self.showLabel.setText(_translate("MainWindow", "查 詢 結 果"))


